# Execution mode (true to Saucelabs, false to local)
#this is currently not being used as it comes directly from testng.xml now
#cloud.execution=true

# Credentials SauceLabs (replace with your keys)
lt.username=oauth-adil.boumaalif-b8958
lt.accesskey=51b94bc3-52b6-416e-a133-427aa6825056
lt.app.id=APP1016044871745163309362583

# Metadados to reports
lt.project=Android Tests
lt.build=Build 1.0